server:
  port: 8080
client:
  url: http://localhost:3000

spring:
  config:
    import:
      - submodule/application-oauth.yaml
      - submodule/application-jwt.yaml
      - submodule/application-mail.yaml
  profiles:
    default: local

frontend:
  url: http://localhost:3000