spring:
  config:
    activate:
      on-profile: prod
    import:
      - submodule/application-db.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: always
