spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://3.35.0.100:3306/heyyo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
