server:
  port: 8080
client:
  url: http://localhost:3000

smtp:
  from: wan2daaa@gmail.com

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: picapark2300@gmail.com
    password: rgjylbuwnpqlxmss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  config:
    import: application-oauth.yaml
  profiles:
    default: local


jwt:
  issuer: wan2daaa@gmail.com
  secret_key: heyyo-backend

frontend:
  url: http://localhost:3000