server:
  port: 8080
client:
  url: http://localhost:3000

spring:
  config:
    import: application-oauth.yaml
  profiles:
    default: local


jwt:
  issuer: wan2daaa@gmail.com
  secret_key: heyyo-backend