server:
  port: 8080
frontend:
  url: http://localhost:3000

spring:
  config:
    import:
      - submodule/application-oauth.yaml
      - submodule/application-jwt.yaml
      - submodule/application-mail.yaml
      - submodule/application-sms.yaml
  profiles:
    default: local
