spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://13.124.135.181:3306/heyyo?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
