name: backend CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SECRET_TOKEN }}
        submodules: true
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build And Test Test
      run: ./gradlew clean bootJar